/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gh.newWorkflow.sw;

public class App {
    public String getGreeting() {
        System.out.println("My name is chase fowler");
        System.out.println("My name is steve winters");
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
